name: Validate package dev index

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Setup test nginx
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Copy arduino directory into /var/www/html
        run: |
          sudo cp -r arduino /var/www/html/

      - name: Start nginx service
        run: |
          sudo systemctl start nginx.service
          sudo systemctl status nginx.service

  validate:
    needs: setup
    name: Validate package index
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install arduino-cli
        uses: giantswarm/install-binary-action@5972d5adf093d659091fa22c136a332453247b43
        with:
          binary: "arduino-cli"
          version: "0.16.1"
          download_url: "https://github.com/arduino/${binary}/releases/download/${version}/${binary}_${version}_Linux_64bit.tar.gz"
          tarball_binary_path: "${binary}"

      - name: "Try installing core sensebox:samd@${{ matrix.version }}"
        run: arduino-cli --additional-urls "file://$(pwd)/package_sensebox-dev_index.json" core install sensebox:samd
