name: Validate stable package index

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup test matrix
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Extract all versions
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(jq -crM '[.packages[0] | .platforms[] | .version ]' package_sensebox_index.json)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  validate:
    needs: setup
    name: Validate stable package index
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: "Try installing core sensebox:samd@${{ matrix.version }}"
        run: arduino-cli --additional-urls "file://$(pwd)/package_sensebox_index.json" core install "sensebox:samd@${{ matrix.version }}"
